version: "3.9"

services:
  database:
    image: postgres:alpine
    container_name: book_store_api_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/data/postgres
    networks:
      - services-network
  api:
    depends_on:
      - database
    build: .
    command: bin/rails s --binding 0.0.0.0
    ports:
    - "3000:3000"
    volumes:
    - .:/application
    stdin_open: true
    tty: true
    networks:
      - services-network
networks:
  services-network:
    driver: bridge
volumes:
  database:
