version: "3.9"

services:
  database:
    image: postgres:alpine
    container_name: book_store_api_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/data/postgres
    networks:
      - services-network
  api_docs:
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    ports:
      - 3001:8080
    volumes:
      - ./:/usr/share/nginx/html/docs/
    environment:
      - "URLS_PRIMARY_NAME=Book Store"
      - "URLS=[
          {url: '/docs/docs/store-api.yaml', name: 'Store API'},
          {url: '/docs/docs/admin-api.yaml', name: 'Admin API'},
        ]"
networks:
  services-network:
    driver: bridge
volumes:
  database:
