default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local_database: &local_database
  host: localhost
  port: 5432
  username: postgres
  password: 1234

development:
  <<:
    - *default
    - *local_database
  database: book_store_api_development

test:
  <<:
    - *default
    - *local_database
  database: book_store_api_test

production:
  <<: *default
  database: <%= ENV["BOOK_STORE_API_DATABASE_NAME"] %>
  username: <%= ENV["BOOK_STORE_API_DATABASE_USER_NAME"] %>
  password: <%= ENV["BOOK_STORE_API_DATABASE_PASSWORD"] %>
  host:     <%= ENV["BOOK_STORE_API_DATABASE_HOST"] %>
