openapi: 3.0.0
info:
  title: Admin Ebook Store API
  description: Admin Ebook Store API
  version: 1.0.0
tags:
  - name: authorization
    description: Authorization of API
servers:
  - url: localhost:3000/
    description: Development server
paths:
  /sign_in:
    post:
      tags:
       - authorization
      summary: Sign In
      description: Sign In.
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponse'
        400:
          description: Bab Request
        401:
          description: Unauthorized
  /sign_out:
    delete:
      security:
        - Authorization: []
      tags:
       - authorization
      summary: Sign Out
      description: Sign Out.
      operationId: signOut
      responses:
        204:
          description: NoContent
components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SignInRequest:
      type: object
      properties:
        admin:
          type: object
          properties:
            email:
              type: string
              description: Admin user email
            password:
              type: string
              description: Admin user password
      example:
        admin:
          email: user.test@gmail.com
          password: "123456"
    SignInResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            token:
              type: string
        meta:
          type: object
          description: JTW token
      example:
        data:
          token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4Iiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNjIzODk5ODQyLCJleHAiOjE2MjM5MDM0NDIsImp0aSI6IjcxMzZhNzRhLTBjZTktNDIyMy1hMzFjLWU3NDhhZmU0MGUzNCJ9.oP9Ho5FZ44TeCT6687pDhBmUL-bWhHxCOuvd45_OJsg
        meta: {}
