openapi: 3.0.0
info:
  title: Ebook Store API
  description: Ebook Store API
  version: 1.0.0
tags:
  - name: authorization
    description: Authorization of API
servers:
  - url: localhost:3000/
    description: Development server
paths:
  /sign_up:
    post:
      tags:
       - authorization
      summary: Sign Up
      description: Sign Up.
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUpResponse'
        400:
          description: Bab Request
        422:
          description: UnprocessableEntity
  /sign_in:
    post:
      tags:
       - authorization
      summary: Sign In
      description: Sign In.
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponse'
        400:
          description: Bab Request
        401:
          description: Unauthorized
  /sign_out:
    delete:
      security:
        - Authorization: []
      tags:
       - authorization
      summary: Sign Out
      description: Sign Out.
      operationId: signOut
      responses:
        204:
          description: NoContent
components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SignUpRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: Info message
        password:
          type: string
          description: Info message
      example:
        email: user.test@gmail.com
        password: "123456"
    SignUpResponse:
      type: object
      properties:
        meta:
          type: object
          properties:
            info:
              type: string
              description: Success message
        data:
          type: object
      example:
        data: null
        meta:
          info: "User created with success."
    SignInRequest:
      type: object
      properties:
        user:
          type: object
          properties:
            email:
              type: string
              description: User email
            password:
              type: string
              description: User password
      example:
        user:
          email: user.test@gmail.com
          password: "123456"
    SignInResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            token:
              type: string
        meta:
          type: object
          description: JTW token
      example:
        data:
          token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4Iiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNjIzODk5ODQyLCJleHAiOjE2MjM5MDM0NDIsImp0aSI6IjcxMzZhNzRhLTBjZTktNDIyMy1hMzFjLWU3NDhhZmU0MGUzNCJ9.oP9Ho5FZ44TeCT6687pDhBmUL-bWhHxCOuvd45_OJsg
        meta: {}
